---
title: "Statement of Contribution"
author: "Abdullah Farouk"
date: '2018-04-05'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Please find below my description of the different tasks each of my team mates and I undertook during the different stages of this project. 

### Describes the tasks and contributions of each of your group members
- **Interesting Project to work on:**  Amy and Young did a lot in this regard. They brought forward a very interesting biological question for us to work on. Additionally they did extensive research on the biological rationale beind some parts of our analysis (for instance removing cross hybridized probes when cleaning the data)

- **Stastistical Analysis:**  Nik and I primarily handled this part of our project. Nik did the inital exploratory analysis, with me complimenting his work with checks of some of our assumptions. We both worked on the machine learning component together. Amy and Young worked on the gene ontology seciton of our analysis pipeline. They helped tie in results from our initial findings to biological functions and help us understand if our results were sensible.

- **Interpretation of Results:**  We all worked on this together. Nik and I would run our findings by Amy and Young to see if they were meaningful, from a biological perspective, that we did not have knowledge of. 

- **Poster:**  Amy and Young did most of the work on this front. They designed the poster and populated it with figures and results from the analysis Nik and I conducted. Additionally they complimented our findings with ties to literature on the subject matter which provided us with confidence in our results. Nik (and I occassionally) contributed by explaining our findings in an easy to understand manner whilst I worked on the graphs. I primarily edited the pictures generated, making sure the axes were well labelled, easy to read and the colours of the graphs tied in well with the colour theme of our poster. 

- **Github Repository organization:**  We as a group worked to ensure each of the folders had a README with a good description of the contents of that folder along with ensuring links were made available to each of them in our root README. 

### Do you think the task assignments were fairly assigned and appropriate given each member’s background and skills? If no, how would you change it?
Yes, I believe they were.

### Explain what are your contributions to the project?
I played an active role in the statistical analysis for this project along with Nikolas. Amy, Young and I worked on the pre processing scripts to clean our datasets. I then helped write the scripts to implement our Machine learning methods, with a focus on testing the K-NN and SVM methods on our datasets along with performing model comparisons. I also wrote code to perform repeated cross validation (CV) though we chose to go with Nik's (correct) code which used repeated nested CV to perform model comparison. Additionally I performed quantitative checks of the normality of our m values matrix. I also cleaned and pre processed an independent GEO dataset we were hoping to test our chosen ML model on. 

With regards to the reports, they were all written in a collaborative manner with each of us taking on a particular section. Whilst I do not remember precisely my contributions to the proposal and progress reports, I did write up, after discussion with my colleagues, the results section of our technial report.

For the poster, I helped by primarily making sure the pics from Nik's initial analysis that were used throughout our poster were well labeled, easy to read and the colours matched well with the theme of our poster.

I also played an active role in organizing our group repository. I worked on populating most of the READMEs in our folders and designing and populating the flow chart in our root README with a consice summary of each of the different analyses undertaken in this project. 


### What worked well and what did not? What was the most challenging or rewarding moment during your group project?
The most challenging aspects in my opinion were the initial stages of the project. As someone without background knowledge in Biology I initially struggled to understand what my group was trying to do. This made it tricky when it came time to figure out how I could contribute. Ironically, jumping right in and trying different things really helped. Actively cleaning the 450k signal intensities dataset helped me understand how this data was collected and how we intended to use them to study preeclempsia. 
There were a lot of rewarding moments during the course of this project. I really enjoyed working on the machine learning scripts. I have new found appreciation of these methods that previously seemed like black boxes to me. I definitely look forward to using them across a wide variety of topics in the future.  Perhaps the  most rewarding moment to me was the poster session. It felt great to see all of our hard work up on display and see how each of our contributions tied together to answer our main research question. 

### How did you find having members of different backgrounds for a scientific project?
It was a very rewarding experience. I learnt a lot about cell biology working with my colleagues from medical genetics. More importantly the interdisciplinary nature of our team helped remind me of how I can leverage my knowledge of statistics and my colleagues, their knowledge of Biology to try and find an interesting solution to a challenging question.

### What have you learned from this group project?
I have learned research can sometimes be unstructured and messy but in the end is a whole lot of fun!

### Any other comments on how the group project could have been structured differently (i.e. delivery requirements, assessment“)
Overall I think the group project is a great way to learn about the material taught in this course. That being said I do think there are a few changes that can be made. Perhaps having more group deliverables in February and March that line up with the material in the seminars taught could improve the kind of work done by the end of the course. For instance having the group deliver their initial findings after learning about Limma and the use of either gene expression or M values as response variables could force students to start working early on on their project. This could potentially allow them to discover potential pitfalls in their analysis earlier on and therefore adress them with an appropriate solution. This would then allow them to present some very interesting findings by the end of the course, by appropriately accounting for these hurdles. 

